# List of gems I want to always keep installed globally
#
# After upgrading/installing ruby, do:
#
#   gem install bundler
#   bundle install --gemfile=~/.ruby/Gemfile
#
source "https://rubygems.org"

gem "cocoapods"
gem "curses"
gem "foreman"
gem "gifme"
gem "god"
gem "nokogiri"
gem "pry"
gem "pry-doc"
gem "rack"
gem "rails"
gem "rspec"
gem "ruby_parser"
gem "savon"
gem "sdoc"
gem "synx"
